stages:
- update

update-to-development:
  stage: update
  script:
    - sudo chmod +x /var/www/html/academy/dev-academyupdate.sh && sudo bash /var/www/html/academy/dev-academyupdate.sh
  only:
    - /-DEV$/
  tags:
    - runner-development


update-to-production:
  stage: update
  script:
    - sudo chmod +x /var/www/html/nolsatu_test/prod-academyupdate.sh && sudo bash /var/www/html/academy/prod-academyupdate.sh
  only:
    - /-PROD$/
  tags:
    - runner-production
