stages:
- update

update-to-development:
  rules:
    - if: $CI_COMMIT_REF_NAME == "master" && '$CI_COMMIT_TAG != null'
  stage: update
  script:
    - sudo chmod +x /var/www/html/academy/dev-academyupdate.sh && sudo bash /var/www/html/academy/dev-academyupdate.sh
#  only:
#    - /-DEV$/
#    - master
  tags:
    - runner-development

update-to-development:
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev.adinusa.id" && '$CI_COMMIT_TAG != null'
  stage: update
  script:
    - sudo chmod +x /var/www/html/devadinusaid/dev-adinusaupdate.sh && sudo bash /var/www/html/devadinusaid/dev-adinusaupdate.sh
#  only:
#    - /-DEV-ADINUSA$/
#    - dev.adinusa.id
  tags:
    - runner-development
